### ISSUE TITLE
Error with restclient

### ISSUE THREAD

**Issue by vedrisko** [aqfaridi/pump_and_dump_bot#13]
I was working just fine with the bot, but suddenly it stopped working. I´m having this error over and over again:

```
c:\ruby yobit_bot.rb "ETH" "1"
"https://yobit.net/api/3/ticker/eth_btc"
C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-mingw32/lib/r
estclient/abstract_response.rb:249:in `exception_with_response': 503 Service Una
vailable (RestClient::ServiceUnavailable)
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient/abstract_response.rb:129:in `return!'
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient/request.rb:831:in `process_result'
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient/request.rb:738:in `block in transmit'
        from C:/Ruby24-x64-2/lib/ruby/2.4.0/net/http.rb:877:in `start'
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient/request.rb:722:in `transmit'
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient/request.rb:158:in `execute'
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient/request.rb:58:in `execute'
        from C:/Ruby24-x64-2/lib/ruby/gems/2.4.0/gems/rest-client-2.1.0.rc1-x64-
mingw32/lib/restclient.rb:66:in `get'
        from yobit_bot.rb:57:in `call_api'
        from yobit_bot.rb:85:in `get_market_summary'
        from yobit_bot.rb:122:in `buy_bot'
        from yobit_bot.rb:225:in `<main>'
```

Any idea what´s going on?

Thanks!

**Comment by DrMabuse-2017** [comment]
First installation...
I have the same Error :-(...
Does somebody has any idea ?

ruby yobit_bot.rb "PAC" "3"
"https://www.yobit.net/api/3/ticker/pac_btc"
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 503 Service Unavailable (RestClient::ServiceUnavailable)
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
        from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
        from /var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
        from yobit_bot.rb:57:in `call_api'
        from yobit_bot.rb:85:in `get_market_summary'
        from yobit_bot.rb:170:in `buy_sell_bot'
        from yobit_bot.rb:225:in `<main>'

**Comment by DrMabuse-2017** [comment]
I have not changed anything, but now it works.

i think this is a problem by yobit?

**Comment by lacostenycoder** [comment]
The error clearly says `RestClient::ServiceUnavailable` Which would indicate the api you're trying to call is unavailable.  See:  https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#503

**Comment by cimp43** [comment]
can you give me ruby yobit_bot.rb but your version because this version right here it's not working with me
