### ISSUE TITLE
Can't start it

### ISSUE THREAD

**Issue by hassassam** [aqfaridi/pump_and_dump_bot#4]
ruby bittrex_bot.rb
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rest-client (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bittrex_bot.rb:1:in `<main>'

**Comment by odemolliens** [comment]
`gem install rest-client`

**Comment by WilcoE** [comment]
You also need:
`gem install colorize`
